// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxWrM4pf2qocjSZiu2kvlyw5Y0Y79e_cM',
    appId: '1:978888448663:web:8fd33b2d3b61e9b80d67d2',
    messagingSenderId: '978888448663',
    projectId: 'modulcodelab3',
    authDomain: 'modulcodelab3.firebaseapp.com',
    storageBucket: 'modulcodelab3.appspot.com',
    measurementId: 'G-DJKXVVXLY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCttytv5VdbLn5Pz2dnSWZXy27BFBsTHt4',
    appId: '1:978888448663:android:1d520b76c78c87160d67d2',
    messagingSenderId: '978888448663',
    projectId: 'modulcodelab3',
    storageBucket: 'modulcodelab3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcDeZKOLOgpKx0exIcLmIFBONOcsC9s88',
    appId: '1:978888448663:ios:6dbf15b6387b63dd0d67d2',
    messagingSenderId: '978888448663',
    projectId: 'modulcodelab3',
    storageBucket: 'modulcodelab3.appspot.com',
    iosBundleId: 'com.example.codelabmodul3pemmob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcDeZKOLOgpKx0exIcLmIFBONOcsC9s88',
    appId: '1:978888448663:ios:6dbf15b6387b63dd0d67d2',
    messagingSenderId: '978888448663',
    projectId: 'modulcodelab3',
    storageBucket: 'modulcodelab3.appspot.com',
    iosBundleId: 'com.example.codelabmodul3pemmob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxWrM4pf2qocjSZiu2kvlyw5Y0Y79e_cM',
    appId: '1:978888448663:web:a057d112438e833e0d67d2',
    messagingSenderId: '978888448663',
    projectId: 'modulcodelab3',
    authDomain: 'modulcodelab3.firebaseapp.com',
    storageBucket: 'modulcodelab3.appspot.com',
    measurementId: 'G-3R1YH5TX7G',
  );
}
